POST http://localhost:8080/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "email": "testing@gmail.com",
    "password": "testing123"
}

###

POST http://localhost:8080/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "testing@gmail.com",
    "password": "testing123"
}

###

GET http://localhost:8080/api/users/current HTTP/1.1
Content-Type: application/json

###


GET http://localhost:8080/api/users/current HTTP/1.1
Content-Type: application/json
Authorization: jwt asdfasdfasdfasdfasdfasdfasdf

###

// Replace the long string with the token 
// string you get from the HTTP request above.

GET http://localhost:8080/api/users/current HTTP/1.1
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RpbmdAZ21haWwuY29tIiwiaWF0IjoxNjM3NjAyNzY4LCJleHAiOjE2Mzc2ODkxNjh9.ec6_5UV-Y9uOWYLINx_Iqd_gOo-65XPXM8KNGp0uPIg

###

POST http://localhost:8080/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "testing@gmail.com",
    "password": "asdflkjasd;lfkjasd;lfkj"
}